"""Autonomous Content Personas — multiple distinct voices for distributed publishing.

One strategy → many personas → varied expressions → broader reach → stronger signals.

Each persona has:
  - Unique tone, vocabulary, and expertise
  - Assigned channels (where they post)
  - History tracking (continuity)
  - Reputation score (boost high performers)
  - Variation enforcement (no duplicate content)
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pydantic import BaseModel, Field

from core.claude import call_claude

log = logging.getLogger(__name__)


class Persona(BaseModel):
    """One distinct voice in the network."""
    id: str
    name: str
    tone: str                          # clear,cost-focused / visual,aspirational / authoritative,local
    expertise: str                     # home improvement / aesthetics / local installations
    goals: list[str] = []             # save money / upgrade look / build trust
    channels: list[str] = []          # reddit, quora, blog, medium, instagram, gbp
    post_count: int = 0
    avg_engagement: float = 0.0
    reputation: float = 5.0           # 0-10
    active: bool = True


class PersonaOutput(BaseModel):
    """Content generated by a specific persona."""
    persona_id: str
    persona_name: str
    channel: str
    tone: str
    title: str = ""
    content: str = ""
    hashtags: list[str] = []
    link_strategy: str = "soft"


class PersonaCampaign(BaseModel):
    """Multi-persona campaign for one topic."""
    keyword: str
    outputs: list[PersonaOutput] = Field(default_factory=list)
    personas_used: int = 0
    channels_covered: list[str] = []


# Default personas for a local service business
DEFAULT_PERSONAS = [
    Persona(
        id="practical",
        name="Practical Homeowner",
        tone="clear, direct, cost-focused",
        expertise="home improvement, budgeting, DIY vs professional",
        goals=["save money", "avoid mistakes", "get best value"],
        channels=["reddit", "quora", "blog"],
    ),
    Persona(
        id="design",
        name="Design Enthusiast",
        tone="visual, aspirational, modern",
        expertise="aesthetics, curb appeal, property value",
        goals=["upgrade home look", "modernize", "impress neighbors"],
        channels=["instagram", "blog", "medium"],
    ),
    Persona(
        id="local_expert",
        name="Local Expert",
        tone="authoritative, knowledgeable, local insider",
        expertise="local climate, building codes, neighborhood expertise",
        goals=["build trust", "establish authority", "educate community"],
        channels=["blog", "gbp", "medium", "quora"],
    ),
    Persona(
        id="tech_savvy",
        name="Smart Home Tech",
        tone="enthusiastic, technical but accessible",
        expertise="smart home, LED technology, app control, automation",
        goals=["showcase innovation", "attract tech-oriented buyers"],
        channels=["reddit", "blog", "social"],
    ),
]


PERSONA_PROMPT = """You are writing as a SPECIFIC persona. Your voice must be DISTINCT from other personas.

PERSONA: {persona_name}
Tone: {tone}
Expertise: {expertise}
Goals: {goals}
Target channel: {channel}

TOPIC: {keyword}
Business: {business_name}
City: {city}

Write content for the {channel} platform AS this persona. The content must:
- Match the persona's tone EXACTLY (not generic)
- Focus on the persona's goals and expertise
- Be appropriate for the {channel} platform's norms
- Be about "{keyword}" in {city}
- NOT sound like marketing copy — sound like a real person with this perspective

Return ONLY JSON:
{{
  "title": "post/article title",
  "content": "the full content (200-500 words depending on platform)",
  "hashtags": ["relevant", "hashtags"],
  "link_strategy": "soft | none"
}}"""


class PersonaSystem:
    """Manages personas and generates multi-voice content."""

    def __init__(self, personas: list[Persona] | None = None):
        self.personas = {p.id: p for p in (personas or DEFAULT_PERSONAS)}

    async def generate_campaign(
        self,
        keyword: str,
        business_name: str,
        city: str,
        max_personas: int = 3,
    ) -> PersonaCampaign:
        """Generate content from multiple personas for one topic."""
        campaign = PersonaCampaign(keyword=keyword)
        channels_used: set[str] = set()

        # Pick personas — prioritize by reputation, ensure channel diversity
        active = sorted(
            [p for p in self.personas.values() if p.active],
            key=lambda p: p.reputation,
            reverse=True,
        )[:max_personas]

        for persona in active:
            # Pick the best channel for this persona (one they haven't used + we haven't covered)
            available = [c for c in persona.channels if c not in channels_used]
            if not available:
                available = persona.channels[:1]
            channel = available[0]

            try:
                output = await self._generate_for_persona(persona, channel, keyword, business_name, city)
                if output:
                    campaign.outputs.append(output)
                    channels_used.add(channel)
            except Exception as e:
                log.error("persona.generate_fail  persona=%s  err=%s", persona.name, e)

        campaign.personas_used = len(campaign.outputs)
        campaign.channels_covered = list(channels_used)

        log.info("persona.campaign  keyword=%s  personas=%d  channels=%s",
                 keyword, campaign.personas_used, campaign.channels_covered)

        return campaign

    async def _generate_for_persona(
        self,
        persona: Persona,
        channel: str,
        keyword: str,
        business_name: str,
        city: str,
    ) -> PersonaOutput | None:
        """Generate content for one persona on one channel."""
        prompt = PERSONA_PROMPT.format(
            persona_name=persona.name,
            tone=persona.tone,
            expertise=persona.expertise,
            goals=", ".join(persona.goals),
            channel=channel,
            keyword=keyword,
            business_name=business_name,
            city=city,
        )

        raw = call_claude(
            prompt,
            system=f"You ARE the '{persona.name}' persona. Write ONLY in their voice. Return ONLY valid JSON.",
            max_tokens=1500,
        )

        if raw.startswith("```"):
            raw = raw.split("\n", 1)[1].rsplit("```", 1)[0].strip()
        start = raw.find("{")
        if start > 0:
            raw = raw[start:]

        try:
            data = json.loads(raw)
            output = PersonaOutput(
                persona_id=persona.id,
                persona_name=persona.name,
                channel=channel,
                tone=persona.tone,
                title=data.get("title", ""),
                content=data.get("content", ""),
                hashtags=data.get("hashtags", []),
                link_strategy=data.get("link_strategy", "soft"),
            )

            persona.post_count += 1
            log.info("persona.generated  persona=%s  channel=%s  len=%d",
                     persona.name, channel, len(output.content))
            return output

        except Exception as e:
            log.error("persona.parse_fail  persona=%s  err=%s", persona.name, e)
            return None

    def boost_performer(self, persona_id: str, engagement: float):
        """Increase reputation for high-performing personas."""
        p = self.personas.get(persona_id)
        if p:
            p.avg_engagement = (p.avg_engagement * (p.post_count - 1) + engagement) / max(p.post_count, 1)
            if engagement > 5:
                p.reputation = min(10, p.reputation + 0.5)
            elif engagement < 2:
                p.reputation = max(1, p.reputation - 0.3)

    def get_summary(self) -> list[dict]:
        return [
            {
                "id": p.id, "name": p.name, "tone": p.tone,
                "channels": p.channels, "posts": p.post_count,
                "reputation": p.reputation, "active": p.active,
            }
            for p in self.personas.values()
        ]
